import {createClient} from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const A=window.NIGHTVERSE;if(!A)throw new Error('Nightverse API missing');const {THREE,scene}=A;
const P3={inventory:['📱 City Phone','🗺️ Digital Map'],job:null,jobTarget:null,ghosts:new Map(),online:1,lastSend:0};
const css=document.createElement('style');css.textContent=`.nv-map{position:absolute;z-index:9;right:18px;bottom:92px;width:190px;padding:9px;border:1px solid #ffffff26;border-radius:16px;background:#07101be8;color:#fff}.nv-map b{font:900 10px Arial}.nv-map canvas{display:block;width:170px;height:170px;margin-top:7px;border-radius:12px;background:#12212c}.nv-tools{position:absolute;z-index:10;right:220px;bottom:25px;display:flex;gap:7px}.nv-tools button{padding:10px 12px;border:1px solid #ffffff20;border-radius:11px;background:#111b28;color:#fff;font:900 9px Arial}.nv-panel{position:absolute;z-index:70;inset:0;display:none;place-items:center;background:#02050bdc;backdrop-filter:blur(8px)}.nv-panel.open{display:grid}.nv-box{width:min(580px,calc(100vw - 24px));max-height:80vh;overflow:auto;padding:18px;border:1px solid #ffffff22;border-radius:20px;background:linear-gradient(145deg,#101827,#231326);color:#fff}.nv-box h2{margin:0;font:900 21px Arial}.nv-box p{color:#98a4b5;font:12px Arial}.nv-list{display:grid;gap:8px;margin-top:13px}.nv-item{padding:12px;border:1px solid #ffffff18;border-radius:12px;background:#151e2c;color:#fff;text-align:left}.nv-item b,.nv-item span{display:block}.nv-item span{margin-top:4px;color:#9ca8ba;font-size:10px}.nv-mobile-only{display:none}.nv-x{float:right;padding:8px 11px;border:0;border-radius:9px;background:#283446;color:#fff}@media(max-width:700px){.locations{display:none}.locations.mobile-open{display:block}.nv-mobile-only{display:block!important}.nv-map{right:10px;bottom:255px;width:132px}.nv-map canvas{width:112px;height:112px}.nv-tools{right:12px;bottom:225px}.nv-tools button{padding:8px;font-size:8px}}`;document.head.appendChild(css);
const map=document.createElement('div');map.className='nv-map';map.innerHTML='<b>🗺️ LIVE CITY MAP</b><canvas width="170" height="170"></canvas>';document.querySelector('.app').appendChild(map);const ctx=map.querySelector('canvas').getContext('2d');
const tools=document.createElement('div');tools.className='nv-tools';tools.innerHTML='<button id="nvInventory">🎒 INVENTORY</button><button id="nvJobs">💼 JOBS</button><button id="nvCity" class="nv-mobile-only">📍 CITY</button><button id="nvMapToggle" class="nv-mobile-only">🗺️ MAP</button>';document.querySelector('.app').appendChild(tools);
const panel=document.createElement('div');panel.className='nv-panel';panel.innerHTML='<div class="nv-box"><button class="nv-x">✕ CLOSE</button><h2 id="nvPanelTitle"></h2><p id="nvPanelText"></p><div id="nvPanelList" class="nv-list"></div></div>';document.querySelector('.app').appendChild(panel);panel.querySelector('.nv-x').onclick=()=>panel.classList.remove('open');
function showPanel(title,text,items){panel.classList.add('open');document.getElementById('nvPanelTitle').textContent=title;document.getElementById('nvPanelText').textContent=text;document.getElementById('nvPanelList').innerHTML=items.join('')}
function inventory(){const p2=A.phase2?.state;if(p2?.gun&&!P3.inventory.includes('🔫 Training Pistol'))P3.inventory.push('🔫 Training Pistol');showPanel('🎒 Inventory','Purchased items and city equipment',P3.inventory.map(x=>`<div class="nv-item"><b>${x}</b><span>Ready to use</span></div>`))}
const jobs=[['Courier Run','Deliver a package across the city',80],['Café Delivery','Take food to Moon Park',60],['Safe Driver','Drive to three city locations',120]];
function jobsPanel(){showPanel('💼 City Jobs','Choose a legal job and earn coins',jobs.map((j,i)=>`<button class="nv-item" data-job="${i}"><b>${j[0]} • 🪙 ${j[2]}</b><span>${j[1]}</span></button>`));document.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>startJob(+b.dataset.job))}
function startJob(i){P3.job=jobs[i];const list=Object.values(A.targets);P3.jobTarget=list[Math.floor(Math.random()*list.length)];panel.classList.remove('open');A.show(`💼 ${P3.job[0]} started • map marker follow करें`)}
document.getElementById('nvInventory').onclick=inventory;document.getElementById('nvJobs').onclick=jobsPanel;document.getElementById('nvCity').onclick=()=>document.querySelector('.locations').classList.toggle('mobile-open');document.getElementById('nvMapToggle').onclick=()=>map.style.display=map.style.display==='none'?'block':'none';
A.building('Couple Lounge',-10,-36,11,8,7,0x6f265e,0xe85cae,'💞');A.registerInteraction('Couple Lounge',()=>{showPanel('💞 Couple Lounge','Consent-based, non-explicit social interactions',[`<button class="nv-item" id="nvCoupleOpen"><b>💌 Open Couple Actions</b><span>Request, hold hands, hug and dance</span></button>`,`<div class="nv-item"><b>🔒 Private Room</b><span>Both adults must accept • fade-to-black only</span></div>`]);document.getElementById('nvCoupleOpen').onclick=()=>{panel.classList.remove('open');document.getElementById('coupleBtn').click()}});
const loc=document.createElement('button');loc.className='loc nv2-loc';loc.innerHTML='<span>💞</span><span><b>Couple Lounge</b><em>Consent-based social room</em></span>';loc.onclick=()=>{const t=A.targets['Couple Lounge'];A.getPlayer().position.set(t.x,0,t.z+6);A.show('📍 Couple Lounge')};document.querySelector('.locations').appendChild(loc);
function dot(x,z,color,r=3){ctx.fillStyle=color;ctx.beginPath();ctx.arc(85+x/45*78,85+z/45*78,r,0,Math.PI*2);ctx.fill()}
function drawMap(){ctx.clearRect(0,0,170,170);ctx.fillStyle='#173d2f';ctx.fillRect(0,0,170,170);ctx.fillStyle='#263341';ctx.fillRect(74,0,22,170);ctx.fillRect(0,74,170,22);ctx.strokeStyle='#ffffff25';ctx.strokeRect(1,1,168,168);Object.values(A.targets).forEach(t=>dot(t.x,t.z,'#fbbf24',2));A.phase2?.vehicles?.forEach(v=>dot(v.position.x,v.position.z,'#38bdf8',3));A.phase2?.cops?.forEach(c=>dot(c.position.x,c.position.z,'#60a5fa',3));P3.ghosts.forEach(g=>dot(g.position.x,g.position.z,'#d946ef',3));if(P3.jobTarget)dot(P3.jobTarget.x,P3.jobTarget.z,'#ffffff',5);const p=A.getPlayer();dot(p.position.x,p.position.z,'#22c55e',5)}
function ghost(id,name){if(P3.ghosts.has(id))return P3.ghosts.get(id);const g=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.42,1.2,6,10),new THREE.MeshStandardMaterial({color:0xd946ef})),head=new THREE.Mesh(new THREE.SphereGeometry(.4,14,10),new THREE.MeshStandardMaterial({color:0xd7a17d}));body.position.y=1.6;head.position.y=2.75;g.add(body,head);g.userData.name=name;scene.add(g);P3.ghosts.set(id,g);return g}
const onlinePill=[...document.querySelectorAll('.pill')].find(x=>x.textContent.includes('PLAYERS'));
async function online(){try{const db=createClient('https://fezyljxjbgefaqroxorl.supabase.co','sb_publishable_UQ0y1axzT6jsesDmz1JHPA_j2budIh3');const ses=(await db.auth.getSession()).data.session,id=ses?.user?.id||crypto.randomUUID(),name=localStorage.getItem('rh3d_player_name')||'Nightverse Player';const ch=db.channel('nightverse-city-v1',{config:{presence:{key:id}}});ch.on('presence',{event:'sync'},()=>{const st=ch.presenceState();P3.online=Math.max(1,Object.keys(st).length);if(onlinePill)onlinePill.innerHTML='<i></i> '+P3.online+(P3.online===1?' PLAYER LIVE':' PLAYERS LIVE')}).on('broadcast',{event:'move'},({payload})=>{if(!payload||payload.id===id)return;const g=ghost(payload.id,payload.name);g.position.set(payload.x||0,0,payload.z||0);g.rotation.y=payload.r||0}).subscribe(async status=>{if(status==='SUBSCRIBED')await ch.track({id,name,online_at:new Date().toISOString()})});P3.send=()=>{const p=A.getPlayer();ch.send({type:'broadcast',event:'move',payload:{id,name,x:p.position.x,z:p.position.z,r:p.rotation.y}})}}catch(e){console.warn('Nightverse online unavailable',e);if(onlinePill)onlinePill.textContent='LOCAL MODE'}}online();
A.onTick(dt=>{drawMap();const p=A.getPlayer();if(P3.job&&P3.jobTarget&&Math.hypot(p.position.x-P3.jobTarget.x,p.position.z-(P3.jobTarget.z+5))<4){A.addCoins(P3.job[2]);A.show(`✅ ${P3.job[0]} complete • +${P3.job[2]} coins`);P3.inventory.push('📦 Completed '+P3.job[0]);P3.job=P3.jobTarget=null}const now=performance.now();if(P3.send&&now-P3.lastSend>180){P3.lastSend=now;P3.send()}});
