const A=window.NIGHTVERSE;
if(!A) throw new Error('Nightverse core API unavailable');
const {THREE,scene,targets}=A;
const state={gun:false,ammo:0,health:100,wanted:0,inCar:false,lastShot:0,lastPoliceHit:0,lastCrime:0,mission:'Visit Gun Shop and buy a pistol'};

const style=document.createElement('style');style.textContent=`
.nv2-hud{position:absolute;z-index:8;left:18px;top:226px;width:235px;padding:11px;border:1px solid #ffffff20;border-radius:14px;background:#08101bd9;backdrop-filter:blur(10px);font:800 10px Arial;color:#fff}.nv2-row{display:flex;justify-content:space-between;margin:5px 0}.nv2-bar{height:7px;border-radius:9px;background:#263244;overflow:hidden}.nv2-bar i{display:block;height:100%;background:linear-gradient(90deg,#22c55e,#84cc16)}.nv2-stars{color:#fbbf24;letter-spacing:2px}.nv2-actions{position:absolute;z-index:8;right:22px;bottom:24px;display:flex;gap:8px}.nv2-actions button{min-height:46px;padding:0 15px;border:1px solid #ffffff25;border-radius:14px;color:#fff;font:900 10px Arial;background:#141d2a}.nv2-actions .shoot{background:linear-gradient(135deg,#dc2626,#f97316)}.nv2-actions .drive{background:linear-gradient(135deg,#2563eb,#06b6d4)}.nv2-modal{position:absolute;z-index:60;inset:0;display:none;place-items:center;background:#02050bd9;backdrop-filter:blur(8px)}.nv2-modal.open{display:grid}.nv2-card{width:min(520px,calc(100vw - 24px));padding:18px;border:1px solid #ffffff24;border-radius:20px;background:linear-gradient(145deg,#101827,#251329);box-shadow:0 35px 90px #000}.nv2-card h2{margin:0 0 4px;font:900 21px Arial}.nv2-card p{color:#9ca8ba;font:12px Arial}.nv2-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-top:14px}.nv2-buy{padding:14px;border:1px solid #ffffff18;border-radius:13px;background:#151e2c;color:#fff;text-align:left}.nv2-buy b,.nv2-buy span{display:block}.nv2-buy span{color:#fbbf24;margin-top:5px;font-size:10px}.nv2-close{float:right;border:0;border-radius:10px;background:#263244;color:#fff;padding:9px 12px}.nv2-banner{position:absolute;z-index:7;left:50%;bottom:20px;transform:translateX(-50%);padding:9px 13px;border-radius:12px;background:#07111ed9;border:1px solid #60a5fa40;color:#cfe8ff;font:800 10px Arial;pointer-events:none}.nv2-loc{display:flex!important}.locations{max-height:72vh;overflow:auto}@media(max-width:700px){.nv2-hud{left:12px;top:185px;width:172px}.nv2-actions{right:14px;bottom:84px;flex-direction:column}.nv2-actions button{width:58px;height:58px;padding:0;border-radius:50%}.nv2-banner{display:none}}
`;document.head.appendChild(style);
const hud=document.createElement('div');hud.className='nv2-hud';hud.innerHTML=`<div class="nv2-row"><span>❤️ HEALTH</span><b id="nvHealth">100</b></div><div class="nv2-bar"><i id="nvHealthBar" style="width:100%"></i></div><div class="nv2-row"><span>🚔 WANTED</span><b id="nvWanted" class="nv2-stars">☆☆☆☆☆</b></div><div class="nv2-row"><span>🔫 WEAPON</span><b id="nvWeapon">UNARMED</b></div><div class="nv2-row"><span>🚗 VEHICLE</span><b id="nvVehicle">ON FOOT</b></div>`;document.querySelector('.app').appendChild(hud);
const actions=document.createElement('div');actions.className='nv2-actions';actions.innerHTML='<button id="nvShoot" class="shoot">🔫 SHOOT</button><button id="nvDrive" class="drive">🚗 DRIVE</button>';document.querySelector('.app').appendChild(actions);
const banner=document.createElement('div');banner.className='nv2-banner';banner.id='nvMission';banner.textContent='MISSION • '+state.mission;document.querySelector('.app').appendChild(banner);
const modal=document.createElement('div');modal.className='nv2-modal';modal.innerHTML=`<div class="nv2-card"><button class="nv2-close">✕ CLOSE</button><h2 id="nvShopTitle">Shop</h2><p id="nvShopText"></p><div id="nvShopItems" class="nv2-grid"></div></div>`;document.querySelector('.app').appendChild(modal);modal.querySelector('.nv2-close').onclick=()=>modal.classList.remove('open');
function ui(){document.getElementById('nvHealth').textContent=Math.max(0,Math.round(state.health));document.getElementById('nvHealthBar').style.width=Math.max(0,state.health)+'%';document.getElementById('nvWanted').textContent='★'.repeat(state.wanted)+'☆'.repeat(5-state.wanted);document.getElementById('nvWeapon').textContent=state.gun?`PISTOL • ${state.ammo}`:'UNARMED';document.getElementById('nvVehicle').textContent=state.inCar?'DRIVING':'ON FOOT';document.getElementById('nvMission').textContent='MISSION • '+state.mission}
function openShop(type){const title=document.getElementById('nvShopTitle'),text=document.getElementById('nvShopText'),items=document.getElementById('nvShopItems');modal.classList.add('open');if(type==='gun'){title.textContent='🔫 Nightverse Gun Shop';text.textContent='Licensed training weapons • shooting range use';items.innerHTML=`<button class="nv2-buy" data-buy="pistol"><b>🔫 Training Pistol</b><span>🪙 200 • includes 20 rounds</span></button><button class="nv2-buy" data-buy="ammo"><b>📦 Ammo Pack</b><span>🪙 50 • 15 rounds</span></button>`}else if(type==='market'){title.textContent='🏪 Neon Market';text.textContent='Health and city supplies';items.innerHTML=`<button class="nv2-buy" data-buy="health"><b>❤️ Health Kit</b><span>🪙 40 • full health</span></button><button class="nv2-buy" data-buy="pass"><b>🚗 Vehicle Pass</b><span>🪙 100 • city driving</span></button>`}else if(type==='food'){title.textContent='☕ Neon Café';text.textContent='Food and energy counter';items.innerHTML=`<button class="nv2-buy" data-buy="meal"><b>🍔 Full Meal</b><span>🪙 30 • restores health</span></button><button class="nv2-buy" data-buy="coffee"><b>☕ Energy Coffee</b><span>🪙 15 • quick recovery</span></button>`}else if(type==='fashion'){title.textContent='👕 Nightverse Fashion';text.textContent='Safe character style effects';items.innerHTML=`<button class="nv2-buy" data-buy="neonstyle"><b>✨ Neon Style Glow</b><span>🪙 80 • permanent this session</span></button><button class="nv2-buy" data-buy="goldstyle"><b>👑 Golden Aura</b><span>🪙 120 • premium effect</span></button>`}else if(type==='garage'){title.textContent='🔧 Turbo Garage';text.textContent='Vehicle upgrades and custom paint';items.innerHTML=`<button class="nv2-buy" data-buy="turbo"><b>⚡ Turbo Upgrade</b><span>🪙 150 • faster driving</span></button><button class="nv2-buy" data-buy="paint"><b>🎨 Neon Paint</b><span>🪙 60 • cyan body color</span></button>`}else{title.textContent='🚔 Police Station';text.textContent='Clear your wanted level legally';items.innerHTML=`<button class="nv2-buy" data-buy="fine"><b>🧾 Pay Fine</b><span>🪙 100 • clears wanted level</span></button><button class="nv2-buy" data-buy="safety"><b>🛡️ Safety Briefing</b><span>FREE • restores health</span></button>`}items.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy))}
let vehiclePass=false,carSpeed=11,styleAura=null;
function buy(x){if(x==='pistol'){if(state.gun)return A.show('Pistol पहले से owned है');if(!A.spendCoins(200))return A.show('कम से कम 200 coins चाहिए');state.gun=true;state.ammo=20;state.mission='Test the pistol at the yellow shooting targets';attachGun()}if(x==='ammo'){if(!A.spendCoins(50))return A.show('50 coins चाहिए');state.ammo+=15}if(x==='health'){if(!A.spendCoins(40))return A.show('40 coins चाहिए');state.health=100}if(x==='pass'){if(!A.spendCoins(100))return A.show('100 coins चाहिए');vehiclePass=true}if(x==='meal'){if(!A.spendCoins(30))return A.show('30 coins चाहिए');state.health=100}if(x==='coffee'){if(!A.spendCoins(15))return A.show('15 coins चाहिए');state.health=Math.min(100,state.health+35)}if(x==='neonstyle'||x==='goldstyle'){const cost=x==='neonstyle'?80:120;if(!A.spendCoins(cost))return A.show(cost+' coins चाहिए');if(styleAura)A.getPlayer().remove(styleAura);styleAura=new THREE.Mesh(new THREE.TorusGeometry(.8,.07,10,30),new THREE.MeshBasicMaterial({color:x==='neonstyle'?0x23dff2:0xffcf3d}));styleAura.rotation.x=Math.PI/2;styleAura.position.y=.12;A.getPlayer().add(styleAura)}if(x==='turbo'){if(!A.spendCoins(150))return A.show('150 coins चाहिए');carSpeed=17}if(x==='paint'){if(!A.spendCoins(60))return A.show('60 coins चाहिए');car.children.forEach(o=>{if(o.isMesh&&o.material?.color&&o.geometry?.type==='BoxGeometry')o.material.color.setHex(0x06b6d4)})}if(x==='fine'){if(!A.spendCoins(100))return A.show('100 coins चाहिए');state.wanted=0}if(x==='safety'){state.health=100}ui();A.show('✅ Purchase complete')}
A.building('Gun Shop',-35,24,10,8,7,0x4d2631,0xd14b55,'🔫');A.building('Neon Market',35,23,10,8,7,0x24506b,0x3ab6d9,'🏪');A.building('Fashion Store',36,0,9,8,7,0x792a68,0xe15ab7,'👕');A.building('Turbo Garage',0,35,12,8,6,0x374151,0x22a9c7,'🔧');A.building('Police Station',-36,0,10,8,7,0x173a67,0x4f8ad9,'🚔');A.registerInteraction('Gun Shop',()=>openShop('gun'));A.registerInteraction('Neon Market',()=>openShop('market'));A.registerInteraction('Neon Café',()=>openShop('food'));A.registerInteraction('Fashion Store',()=>openShop('fashion'));A.registerInteraction('Turbo Garage',()=>openShop('garage'));A.registerInteraction('Police Station',()=>openShop('police'));
const locations=document.querySelector('.locations');[['Gun Shop','🔫','Weapons & range'],['Neon Market','🏪','Health & vehicle pass'],['Fashion Store','👕','Style effects'],['Turbo Garage','🔧','Car upgrades'],['Police Station','🚔','Fine & safety']].forEach(([name,ico,sub])=>{const b=document.createElement('button');b.className='loc nv2-loc';b.innerHTML=`<span>${ico}</span><span><b>${name}</b><em>${sub}</em></span>`;b.onclick=()=>{const t=targets[name],p=A.getPlayer();p.position.set(t.x,0,t.z+6);A.show('📍 '+name)};locations.appendChild(b)});
function mesh(g,c){const m=new THREE.Mesh(g,A.mat(c));m.castShadow=m.receiveShadow=true;return m}
function makeCar(){const g=new THREE.Group(),body=mesh(new THREE.BoxGeometry(3.1,.7,5.2),0x1d67d8),cab=mesh(new THREE.BoxGeometry(2.45,.8,2.5),0x16365e);body.position.y=.75;cab.position.set(0,1.45,-.2);g.add(body,cab);for(const x of [-1.45,1.45])for(const z of [-1.65,1.65]){const w=mesh(new THREE.CylinderGeometry(.48,.48,.35,16),0x111318);w.rotation.z=Math.PI/2;w.position.set(x,.48,z);g.add(w)}g.position.set(7,0,16);scene.add(g);return g}const car=makeCar();
function toggleCar(){const p=A.getPlayer(),d=p.position.distanceTo(car.position);if(!state.inCar){if(!vehiclePass)return A.show('🏪 Neon Market से Vehicle Pass खरीदें');if(d>4)return A.show('🚗 Blue car के पास जाएँ');state.inCar=true;p.visible=false;A.show('🚗 Driving mode • WASD / Arrows')}else{state.inCar=false;p.visible=true;p.position.x+=2;A.show('Vehicle exited')}ui()}
function attachGun(){const p=A.getPlayer();if(p.userData.nvGun)return;const g=mesh(new THREE.BoxGeometry(.16,.18,.75),0x23272f);g.position.set(.42,2.15,.5);p.add(g);p.userData.nvGun=g}
const range=[];for(let i=0;i<4;i++){const t=mesh(new THREE.BoxGeometry(.12,1.4,1.1),0xe7bd2c);t.position.set(-28+i*3,1.1,14);scene.add(t);range.push(t)}
function fire(){const now=performance.now(),p=A.getPlayer();if(now-state.lastShot<280)return;if(!state.gun)return A.show('🔫 पहले Gun Shop से pistol खरीदें');if(!state.ammo)return A.show('Ammo खत्म • Gun Shop जाएँ');state.lastShot=now;state.ammo--;const dir=new THREE.Vector3(Math.sin(p.rotation.y),0,Math.cos(p.rotation.y)),start=p.position.clone().add(new THREE.Vector3(0,2.1,0)),end=start.clone().addScaledVector(dir,18),geo=new THREE.BufferGeometry().setFromPoints([start,end]),line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0xffdd55}));scene.add(line);setTimeout(()=>{scene.remove(line);geo.dispose();line.material.dispose()},90);let hitTarget=null,best=2;range.forEach(t=>{if(!t.visible)return;const v=t.position.clone().sub(p.position),along=v.dot(dir),side=v.clone().addScaledVector(dir,-along).length();if(along>0&&along<18&&side<best){hitTarget=t;best=side}});if(hitTarget){hitTarget.visible=false;A.addCoins(25);state.mission=range.every(t=>!t.visible)?'Range cleared! Find a car and buy a Vehicle Pass':'Hit all yellow range targets';A.show('🎯 Target hit • +25 coins')}else{let victim=null,vd=1.3;A.npcs.forEach(n=>{const v=n.position.clone().sub(p.position),along=v.dot(dir),side=v.clone().addScaledVector(dir,-along).length();if(along>0&&along<14&&side<vd){victim=n;vd=side}});if(victim){victim.userData.hitUntil=now+900;state.wanted=Math.min(5,state.wanted+1);state.lastCrime=now;A.show('🚨 Crime reported • Police alerted')}else A.show('🔫 Shot fired')}ui()}
function makeCop(x,z){const g=new THREE.Group(),torso=mesh(new THREE.CapsuleGeometry(.48,1.1,6,10),0x164e9a),head=mesh(new THREE.SphereGeometry(.42,16,12),0xd7a17d);torso.position.y=1.75;head.position.y=2.85;g.add(torso,head);for(const sx of [-.25,.25]){const leg=mesh(new THREE.CapsuleGeometry(.13,.75,5,8),0x172033);leg.position.set(sx,.65,0);g.add(leg)}g.position.set(x,0,z);scene.add(g);return g}const cops=[makeCop(30,-10),makeCop(-30,-8)];
function arrest(){state.health=100;state.wanted=0;state.inCar=false;const p=A.getPlayer();p.visible=true;p.position.set(0,0,10);if(A.getCoins()>=100)A.spendCoins(100);A.show('🚔 Arrested • 100 coin fine');ui()}
function phaseTick(dt){const p=A.getPlayer();if(state.inCar){car.position.copy(p.position);car.rotation.y=p.rotation.y;const k=A.getKeys();let dx=(k.has('d')||k.has('arrowright')?1:0)-(k.has('a')||k.has('arrowleft')?1:0),dz=(k.has('s')||k.has('arrowdown')?1:0)-(k.has('w')||k.has('arrowup')?1:0);const l=Math.hypot(dx,dz);if(l>.1){p.position.x=THREE.MathUtils.clamp(p.position.x+dx/l*carSpeed*dt,-42,42);p.position.z=THREE.MathUtils.clamp(p.position.z+dz/l*carSpeed*dt,-42,42)}}if(state.wanted>0){cops.forEach(c=>{const v=p.position.clone().sub(c.position),d=v.length();if(d>.1)c.position.addScaledVector(v.normalize(),dt*(2.4+state.wanted*.7));c.lookAt(p.position.x,c.position.y,p.position.z);if(d<1.7&&performance.now()-state.lastPoliceHit>900){state.lastPoliceHit=performance.now();state.health-=12;A.show('🚔 Police hit • Escape!');if(state.health<=0)arrest();ui()}});if(performance.now()-state.lastCrime>30000){state.wanted=Math.max(0,state.wanted-1);state.lastCrime=performance.now();ui()}}}
A.onTick(phaseTick);document.getElementById('nvShoot').onclick=fire;document.getElementById('nvDrive').onclick=toggleCar;addEventListener('keydown',e=>{if(e.repeat)return;if(e.key.toLowerCase()==='g')fire();if(e.key.toLowerCase()==='v')toggleCar()});ui();A.show('✨ Phase 2 loaded • Gun Shop, car, police and market ready');
