/* RATHOD HUB Hybrid Offline Mode — IndexedDB + mobile storage + sync queue */
(function(){
'use strict';
if(window.__RH_OFFLINE__)return;window.__RH_OFFLINE__=1;
const DB_NAME='rathod_hub_offline',DB_VERSION=1,MAX_FILE=100*1024*1024;
let handle=null,syncing=false;
const $=id=>document.getElementById(id),uid=()=>String(window.user?.id||'guest'),day=()=>new Date().toISOString().slice(0,10);
function openDB(){if(handle)return handle;handle=new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('snapshots'))d.createObjectStore('snapshots',{keyPath:'key'});if(!d.objectStoreNames.contains('queue'))d.createObjectStore('queue',{keyPath:'id'});if(!d.objectStoreNames.contains('files'))d.createObjectStore('files',{keyPath:'id'});if(!d.objectStoreNames.contains('drafts'))d.createObjectStore('drafts',{keyPath:'key'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return handle}
async function put(store,value){const d=await openDB();return new Promise((res,rej)=>{const t=d.transaction(store,'readwrite'),r=t.objectStore(store).put(value);r.onsuccess=()=>res(value);r.onerror=()=>rej(r.error)})}
async function get(store,key){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).get(key);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function all(store){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(store).objectStore(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function del(store,key){const d=await openDB();return new Promise((res,rej)=>{const r=d.transaction(store,'readwrite').objectStore(store).delete(key);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function notify(t,ok=true){if(typeof window.toast==='function')window.toast(t,ok)}
async function persist(){try{if(navigator.storage?.persist)await navigator.storage.persist()}catch(e){}}
function localSnapshot(){const local={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&(/^(rh_|rathod_)/.test(k)))local[k]=localStorage.getItem(k)}let focus=null;try{focus=typeof readFocusStats==='function'?readFocusStats():null}catch(e){}return{key:'app:'+uid(),userId:uid(),savedAt:new Date().toISOString(),profile:window.profile?{id:profile.id,name:profile.name,xp:profile.xp,role:profile.role}:null,focus,local}}
async function saveSnapshot(){try{await put('snapshots',localSnapshot());updateStatus()}catch(e){console.info('Offline snapshot skipped',e)}}
async function restoreSnapshot(){if(navigator.onLine)return;try{const snap=await get('snapshots','app:'+uid());if(!snap)return;Object.entries(snap.local||{}).forEach(([k,v])=>{if(localStorage.getItem(k)==null)localStorage.setItem(k,v)});window.dispatchEvent(new CustomEvent('rh-offline-restored',{detail:snap}));notify('Offline saved data restore हो गया ✓')}catch(e){}}
async function enqueue(type,payload){const row={id:(crypto.randomUUID?.()||('q_'+Date.now()+'_'+Math.random())),userId:uid(),type,payload,createdAt:new Date().toISOString(),attempts:0};await put('queue',row);updateStatus();return row}
async function syncQueue(){if(syncing||!navigator.onLine||!window.db||!window.user)return;syncing=true;try{const rows=(await all('queue')).filter(x=>x.userId===uid());for(const row of rows){try{if(row.type==='todo.create'){const r=await db.from('daily_todos').insert({...row.payload,user_id:user.id});if(r.error)throw r.error}else if(row.type==='draft.snapshot'){}await del('queue',row.id)}catch(e){row.attempts=(row.attempts||0)+1;row.lastError=String(e?.message||e);await put('queue',row)}}if(rows.length)notify('Offline activity sync complete ✓')}finally{syncing=false;updateStatus()}}
function ensureIndicator(){if($('rh-offline-indicator'))return;const b=document.createElement('button');b.id='rh-offline-indicator';b.type='button';b.style.cssText='position:fixed;right:12px;bottom:82px;z-index:9000;border:1px solid rgba(255,255,255,.16);border-radius:999px;padding:8px 11px;background:#111827;color:#fff;font:800 10px system-ui;box-shadow:0 8px 25px rgba(0,0,0,.35)';b.onclick=()=>{const p=$('rh-offline-library');if(p){p.scrollIntoView({behavior:"smooth"});if(typeof window.switchTab==='function')window.switchTab('vault')}};document.body.appendChild(b)}
async function updateStatus(){ensureIndicator();const b=$('rh-offline-indicator');if(!b)return;let n=0;try{n=(await all('queue')).filter(x=>x.userId===uid()).length}catch(e){}b.textContent=navigator.onLine?`🟢 ONLINE${n?' • '+n+' syncing':''}`:`🟠 OFFLINE${n?' • '+n+' pending':''}`;b.style.background=navigator.onLine?'#064e3b':'#7c2d12'}
function installDrafts(){document.querySelectorAll('input[type="text"],textarea').forEach(el=>{if(!el.id||el.dataset.rhOfflineDraft)return;el.dataset.rhOfflineDraft='1';const key='draft:'+uid()+':'+el.id;get('drafts',key).then(x=>{if(x?.value&&!el.value)el.value=x.value}).catch(()=>{});el.addEventListener('input',()=>{clearTimeout(el.__rhDraftTimer);el.__rhDraftTimer=setTimeout(()=>put('drafts',{key,value:el.value,savedAt:new Date().toISOString()}),400)})})}
function interceptOfflineTodo(){if(document.documentElement.dataset.rhOfflineTodo)return;document.documentElement.dataset.rhOfflineTodo='1';document.addEventListener('submit',async e=>{if(navigator.onLine||e.target?.id!=='todo-form')return;e.preventDefault();e.stopImmediatePropagation();const title=$('todo-title')?.value.trim();if(!title)return;const payload={todo_date:day(),title,subject:$('todo-subject')?.value||'Revision',done:false};await enqueue('todo.create',payload);const list=$('todo-list');if(list)list.insertAdjacentHTML('afterbegin',`<div class="rounded-xl border border-amber-400/20 bg-amber-500/5 p-3 text-xs"><b>⏳ ${String(title).replace(/[<>]/g,'')}</b><div class="text-[9px] text-amber-300">Offline saved • internet आने पर sync होगा</div></div>`);e.target.reset();notify('Task mobile storage में save हुआ ✓')},true)}
function ensureLibrary(){const vault=$('section-vault');if(!vault||$('rh-offline-library'))return;const card=document.createElement('div');card.id='rh-offline-library';card.className='rounded-3xl border border-emerald-400/25 bg-gradient-to-br from-slate-950 via-emerald-950/20 to-cyan-950/20 p-5 sm:p-6';card.innerHTML='<div class="flex flex-wrap items-start justify-between gap-3"><div><div class="text-[9px] font-black tracking-[.2em] text-emerald-300">MOBILE OFFLINE STORAGE</div><h3 class="mt-1 text-xl font-black">📥 Offline Library</h3><p class="mt-1 text-[10px] text-slate-400">PDF, notes और files इसी device में save रहेंगी। Live/AI features को internet चाहिए।</p></div><label class="cursor-pointer rounded-xl bg-emerald-600 px-4 py-2.5 text-xs font-black">Save File Offline<input id="rh-offline-file" type="file" class="hidden" multiple></label></div><div id="rh-offline-file-list" class="mt-4 grid gap-2"></div>';vault.prepend(card);$('rh-offline-file').addEventListener('change',saveFiles);renderFiles()}
async function saveFiles(e){for(const file of [...e.target.files]){if(file.size>MAX_FILE){notify(`${file.name}: maximum 100 MB`,false);continue}try{await put('files',{id:uid()+':'+Date.now()+':'+Math.random(),userId:uid(),name:file.name,type:file.type,size:file.size,savedAt:new Date().toISOString(),blob:file});notify(`${file.name} offline save हुआ ✓`)}catch(err){notify('Storage full या file save failed',false)}}e.target.value='';renderFiles()}
async function renderFiles(){const box=$('rh-offline-file-list');if(!box)return;const rows=(await all('files')).filter(x=>x.userId===uid()).sort((a,b)=>b.savedAt.localeCompare(a.savedAt));box.innerHTML=rows.length?rows.map(x=>`<div class="flex items-center gap-3 rounded-xl border border-white/10 bg-black/20 p-3"><span>📄</span><div class="min-w-0 flex-1"><b class="block truncate text-xs">${String(x.name).replace(/[<>]/g,'')}</b><span class="text-[9px] text-slate-500">${(x.size/1048576).toFixed(1)} MB • device storage</span></div><button data-open="${x.id}" class="rounded-lg bg-cyan-600 px-3 py-2 text-[9px] font-black">Open</button><button data-del="${x.id}" class="rounded-lg bg-red-600 px-3 py-2 text-[9px] font-black">Delete</button></div>`).join(''):'<div class="rounded-xl border border-dashed border-slate-700 p-5 text-center text-xs text-slate-500">कोई offline file save नहीं है।</div>';box.querySelectorAll('[data-open]').forEach(b=>b.onclick=async()=>{const x=await get('files',b.dataset.open);if(x?.blob)window.open(URL.createObjectURL(x.blob),'_blank')});box.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{await del('files',b.dataset.del);renderFiles()})}
function run(){persist();ensureIndicator();ensureLibrary();installDrafts();interceptOfflineTodo();saveSnapshot();if(navigator.onLine)syncQueue();updateStatus()}
window.RathodOffline={saveSnapshot,restoreSnapshot,enqueue,sync:syncQueue,files:()=>all('files')};window.addEventListener('online',()=>{notify('Internet वापस आ गया—sync शुरू ✓');syncQueue()});window.addEventListener('offline',()=>{notify('Offline mode चालू—data device में save होगा');saveSnapshot();updateStatus()});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{run();restoreSnapshot()});else{run();restoreSnapshot()}setInterval(run,30000);new MutationObserver(()=>{clearTimeout(window.__rhOfflineTimer);window.__rhOfflineTimer=setTimeout(()=>{ensureLibrary();installDrafts()},200)}).observe(document.documentElement,{childList:true,subtree:true});
})();