(function(){
'use strict';
const W=960,H=600,avatars=['🧑‍⚕️','👩‍⚕️','🧑‍🚀','🧙','🥷','🦸','🧑‍🎓','🤖'];
const scenes={city:{label:'HUB City',sky:'#07141b',ground:'#123829'},park:{label:'Moon Park',sky:'#090f1c',ground:'#183a31'},cafe:{label:'Neon Café',sky:'#160d17',ground:'#38251f'},arcade:{label:'Game Zone',sky:'#0b0820',ground:'#251546'}};
let ch=null,running=false,frame=0,last=0,lastTrack=0,keys=new Set(),target=null,people=new Map(),feed=[],muted=new Set();
let me={x:480,y:380,scene:'city',avatar:'🧑‍⚕️',color:'#ec4899',bubble:'',name:'Player',roomOwner:null,furniture:[]};
const $=id=>document.getElementById(id),clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function currentUser(){try{return typeof user!=='undefined'?user:null}catch{return null}}
function currentProfile(){try{return typeof profile!=='undefined'?profile:null}catch{return null}}
function currentDb(){try{return typeof db!=='undefined'?db:null}catch{return null}}
function uid(){return currentUser()?.id||'guest'}
function roomKey(){return `rh_world_room_${uid()}`}
function avatarKey(){return `rh_world_avatar_${uid()}`}
function defaultFurniture(){return[{kind:'bed',x:250,y:250},{kind:'sofa',x:610,y:360},{kind:'plant',x:760,y:180}]}
function loadPrefs(){try{me.avatar=localStorage.getItem(avatarKey())||avatars[0];me.furniture=JSON.parse(localStorage.getItem(roomKey())||'null')||defaultFurniture()}catch{me.furniture=defaultFurniture()}me.name=currentProfile()?.name||currentUser()?.email?.split('@')[0]||'Player'}
function visible(){return !$('rh-world-shell')?.classList.contains('hidden')}
function safeText(v,n=80){return String(v||'').replace(/[<>]/g,'').trim().slice(0,n)}
function state(){return{user_id:uid(),name:me.name,avatar:me.avatar,color:me.color,x:Math.round(me.x),y:Math.round(me.y),scene:me.scene,bubble:me.bubble,roomOwner:me.roomOwner,furniture:me.furniture,online_at:new Date().toISOString()}}
async function track(force=false){if(!ch||!running)return;const now=Date.now();if(!force&&now-lastTrack<220)return;lastTrack=now;try{await ch.track(state())}catch{}}
function sync(){people.clear();if(ch){Object.values(ch.presenceState()).flat().forEach(p=>{if(p?.user_id&&p.user_id!==uid())people.set(String(p.user_id),p)})}renderPeople();renderCount()}
function renderCount(){const same=[...people.values()].filter(p=>p.scene===me.scene).length+1;const all=people.size+1;if($('rh-world-count'))$('rh-world-count').textContent=`${same} HERE • ${all} ONLINE`;if($('rh-world-launch-count'))$('rh-world-launch-count').textContent=`${all} live`}
function esc(v){const d=document.createElement('div');d.textContent=String(v||'');return d.innerHTML}
function renderPeople(){const box=$('rh-world-people');if(!box)return;const rows=[{...me,user_id:uid(),self:true},...people.values()];box.innerHTML=rows.map(p=>`<div class="rh-world-person"><div class="rh-world-avatar-mini">${esc(p.avatar||'🙂')}</div><div class="rh-world-person-info"><b>${esc(p.name||'Player')}${p.self?' • You':''}</b><span>${esc(sceneLabel(p.scene))}</span></div>${!p.self?`<button class="rh-world-visit" onclick="rhWorldVisit('${esc(p.user_id)}')">Visit</button>`:''}</div>`).join('')}
function sceneLabel(s){if(String(s||'').startsWith('room:'))return 'Personal Room';return scenes[s]?.label||'HUB City'}
async function initChannel(){if(ch||!currentDb()||!currentUser())return;if(window.rhWorldChannel)try{await db.removeChannel(window.rhWorldChannel)}catch{};ch=db.channel('rathod-world-v1',{config:{presence:{key:uid()},broadcast:{self:false}}});window.rhWorldChannel=ch;ch.on('presence',{event:'sync'},sync).on('presence',{event:'join'},sync).on('presence',{event:'leave'},sync).on('broadcast',{event:'world-chat'},({payload})=>receiveChat(payload)).subscribe(async status=>{if(status==='SUBSCRIBED'){await track(true);addFeed('World','Connected to RATHOD WORLD 🌍');sync()}})}
function addFeed(name,text){feed.push({name:safeText(name,30),text:safeText(text,100)});feed=feed.slice(-30);const box=$('rh-world-feed');if(box){box.innerHTML=feed.map(m=>`<div class="rh-world-msg"><b>${esc(m.name)}:</b> ${esc(m.text)}</div>`).join('');box.scrollTop=box.scrollHeight}}
function receiveChat(p){if(!p||p.user_id===uid()||muted.has(String(p.user_id))||p.scene!==me.scene)return;addFeed(p.name||'Player',p.text||'');const person=people.get(String(p.user_id));if(person){person.bubble=safeText(p.text);person.bubble_until=Date.now()+5000}}
async function sendChat(){const input=$('rh-world-chat-input'),text=safeText(input?.value);if(!text||!ch)return;if(input)input.value='';me.bubble=text;addFeed(me.name,text);await track(true);try{await ch.send({type:'broadcast',event:'world-chat',payload:{user_id:uid(),name:me.name,scene:me.scene,text}})}catch{};setTimeout(()=>{if(me.bubble===text){me.bubble='';track(true)}},5000)}
function tabState(){document.querySelectorAll('[data-rh-world-scene]').forEach(b=>b.classList.toggle('active',(b.dataset.rhWorldScene==='room-self'?`room:${uid()}`:b.dataset.rhWorldScene)===me.scene));$('rh-world-room-tools')?.classList.toggle('active',me.scene===`room:${uid()}`);if($('rh-world-place'))$('rh-world-place').textContent=sceneLabel(me.scene)}
async function setScene(scene){me.scene=scene;me.roomOwner=String(scene).startsWith('room:')?String(scene).slice(5):null;me.x=480;me.y=390;target=null;tabState();renderPeople();await track(true)}
function visit(id){const p=people.get(String(id));if(!p)return window.toast?.('Player अभी offline है.',false);setScene(`room:${id}`);addFeed('World',`${p.name||'Friend'} के room में आए`)}
function chooseAvatar(a){if(!avatars.includes(a))return;me.avatar=a;localStorage.setItem(avatarKey(),a);document.querySelectorAll('[data-rh-avatar]').forEach(b=>b.classList.toggle('active',b.dataset.rhAvatar===a));track(true)}
function furnitureIcon(k){return({bed:'🛏️',sofa:'🛋️',plant:'🪴',lamp:'💡',game:'🕹️',table:'🪑'})[k]||'📦'}
function addFurniture(kind){if(me.scene!==`room:${uid()}`)return window.toast?.('पहले My Room खोलें.',false);if(me.furniture.length>=18)return window.toast?.('Room full है.',false);me.furniture.push({kind,x:180+Math.random()*600,y:190+Math.random()*280});saveRoom()}
function clearRoom(){if(me.scene!==`room:${uid()}`||!confirm('Room furniture clear करें?'))return;me.furniture=[];saveRoom()}
function saveRoom(){localStorage.setItem(roomKey(),JSON.stringify(me.furniture));track(true);window.toast?.('Room design saved ✓')}
function drawDiamond(ctx,x,y,w,h,color,stroke){ctx.beginPath();ctx.moveTo(x,y-h/2);ctx.lineTo(x+w/2,y);ctx.lineTo(x,y+h/2);ctx.lineTo(x-w/2,y);ctx.closePath();ctx.fillStyle=color;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function roundRect(ctx,x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function building(ctx,x,y,w,h,color,label,emoji){ctx.fillStyle='rgba(0,0,0,.28)';ctx.fillRect(x+12,y+18,w,h);roundRect(ctx,x,y,w,h,14,color,'rgba(255,255,255,.15)');ctx.fillStyle='rgba(255,255,255,.08)';ctx.fillRect(x+12,y+16,w-24,10);ctx.font='28px system-ui';ctx.fillText(emoji,x+w/2-15,y+h/2);ctx.fillStyle='#fff';ctx.font='800 13px system-ui';ctx.textAlign='center';ctx.fillText(label,x+w/2,y+h-16);ctx.textAlign='left'}
function drawCity(ctx){ctx.fillStyle='#0d2c25';ctx.fillRect(0,0,W,H);ctx.fillStyle='#18212c';ctx.fillRect(0,255,W,100);ctx.fillRect(430,0,100,H);ctx.strokeStyle='rgba(255,255,255,.16)';ctx.setLineDash([18,16]);ctx.beginPath();ctx.moveTo(0,305);ctx.lineTo(W,305);ctx.moveTo(480,0);ctx.lineTo(480,H);ctx.stroke();ctx.setLineDash([]);building(ctx,70,70,210,135,'#172033','NEON CAFÉ','☕');building(ctx,675,75,205,130,'#241a3b','GAME ZONE','🕹️');building(ctx,65,405,220,125,'#16372f','MOON PARK','🌙');building(ctx,670,402,215,128,'#35201f','ROOMS','🏠');for(let i=0;i<12;i++){ctx.fillStyle=i%2?'#1d5b42':'#2d7351';ctx.beginPath();ctx.arc(330+(i%3)*300,70+Math.floor(i/3)*155,15,0,Math.PI*2);ctx.fill()}}
function drawPark(ctx){ctx.fillStyle='#123b2e';ctx.fillRect(0,0,W,H);ctx.fillStyle='#1d503c';ctx.beginPath();ctx.ellipse(480,320,360,205,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#164b58';ctx.beginPath();ctx.ellipse(480,330,145,82,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#67e8f9';ctx.globalAlpha=.25;ctx.stroke();ctx.globalAlpha=1;for(let i=0;i<20;i++){const x=80+(i*137)%810,y=70+(i*83)%450;ctx.font='28px system-ui';ctx.fillText(i%3?'🌲':'🌸',x,y)}ctx.fillStyle='#fff';ctx.font='900 24px system-ui';ctx.fillText('MOON PARK',30,45)}
function drawCafe(ctx){ctx.fillStyle='#24151a';ctx.fillRect(0,0,W,H);for(let x=0;x<W;x+=80)for(let y=0;y<H;y+=80){ctx.fillStyle=(x/80+y/80)%2?'#302027':'#251a22';ctx.fillRect(x,y,80,80)}roundRect(ctx,130,90,700,110,20,'#3b202c','#ec4899');ctx.fillStyle='#fff';ctx.font='900 26px system-ui';ctx.fillText('☕ NEON CAFÉ',340,150);for(let i=0;i<7;i++){ctx.font='38px system-ui';ctx.fillText('🪑',130+i*112,360+(i%2)*80)}}
function drawArcade(ctx){ctx.fillStyle='#100b28';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(168,85,247,.18)';for(let x=0;x<W;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=50){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.fillStyle='#fff';ctx.font='900 26px system-ui';ctx.fillText('🕹️ RATHOD ARCADE',30,48);for(let i=0;i<8;i++)building(ctx,70+(i%4)*220,110+Math.floor(i/4)*250,150,150,i%2?'#241446':'#113047',['RACE','PARKOUR','HIDE','FOOTBALL'][i%4],'🎮')}
function roomFurniture(){if(me.scene===`room:${uid()}`)return me.furniture;const owner=people.get(String(me.roomOwner));return Array.isArray(owner?.furniture)?owner.furniture:defaultFurniture()}
function drawRoom(ctx){ctx.fillStyle='#171522';ctx.fillRect(0,0,W,H);drawDiamond(ctx,480,320,760,410,'#26263a','#4c4567');ctx.fillStyle='#fff';ctx.font='900 22px system-ui';ctx.fillText(me.scene===`room:${uid()}`?'🏠 MY ROOM':`🏠 ${safeText(people.get(String(me.roomOwner))?.name||'Friend',20)}'S ROOM`,28,44);roomFurniture().forEach(f=>{ctx.font='48px system-ui';ctx.textAlign='center';ctx.fillText(furnitureIcon(f.kind),f.x,f.y);ctx.textAlign='left'})}
function bubble(ctx,p){const text=safeText(p.bubble,38);if(!text)return;ctx.font='700 12px system-ui';const w=Math.min(250,ctx.measureText(text).width+24),x=clamp(p.x-w/2,8,W-w-8),y=p.y-76;roundRect(ctx,x,y,w,34,12,'rgba(5,8,14,.92)','rgba(255,255,255,.18)');ctx.fillStyle='#fff';ctx.textAlign='center';ctx.fillText(text.slice(0,36),x+w/2,y+21);ctx.textAlign='left'}
function avatar(ctx,p,self=false){ctx.save();ctx.translate(p.x,p.y);ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(0,18,23,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.color||'#8b5cf6';ctx.beginPath();ctx.arc(0,0,self?24:21,0,Math.PI*2);ctx.fill();ctx.strokeStyle=self?'#67e8f9':'rgba(255,255,255,.45)';ctx.lineWidth=self?3:2;ctx.stroke();ctx.font=`${self?30:27}px system-ui`;ctx.textAlign='center';ctx.fillText(p.avatar||'🙂',0,10);ctx.fillStyle='#fff';ctx.font='800 11px system-ui';ctx.fillText((p.name||'Player').slice(0,16),0,42);ctx.restore();bubble(ctx,p)}
function updateCamera(c){if(window.innerWidth>520){c.style.left='';return}const stage=c.parentElement,display=720,view=stage?.clientWidth||360;const wanted=view/2-(me.x/W)*display;c.style.left=`${Math.min(0,Math.max(view-display,wanted))}px`}
function draw(){const c=$('rh-world-canvas');if(!c)return;updateCamera(c);const ctx=c.getContext('2d');ctx.clearRect(0,0,W,H);if(me.scene==='city')drawCity(ctx);else if(me.scene==='park')drawPark(ctx);else if(me.scene==='cafe')drawCafe(ctx);else if(me.scene==='arcade')drawArcade(ctx);else drawRoom(ctx);[...people.values()].filter(p=>p.scene===me.scene).sort((a,b)=>(a.y||0)-(b.y||0)).forEach(p=>{if(p.bubble_until&&p.bubble_until<Date.now())p.bubble='';avatar(ctx,p,false)});avatar(ctx,me,true)}
function move(dt){let dx=0,dy=0;if(keys.has('arrowleft')||keys.has('a'))dx--;if(keys.has('arrowright')||keys.has('d'))dx++;if(keys.has('arrowup')||keys.has('w'))dy--;if(keys.has('arrowdown')||keys.has('s'))dy++;if(target){const tx=target.x-me.x,ty=target.y-me.y,d=Math.hypot(tx,ty);if(d<7)target=null;else{dx=tx/d;dy=ty/d}}if(!dx&&!dy)return;const m=Math.hypot(dx,dy)||1;me.x=clamp(me.x+dx/m*190*dt,35,W-35);me.y=clamp(me.y+dy/m*190*dt,65,H-55);track()}
function loop(t){if(!running)return;const dt=Math.min(.04,(t-last)/1000||0);last=t;if(visible())move(dt);draw();frame=requestAnimationFrame(loop)}
function canvasTap(e){const c=e.currentTarget,r=c.getBoundingClientRect();target={x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}}
function dpad(dir,on){const map={up:'arrowup',down:'arrowdown',left:'arrowleft',right:'arrowright'};if(on){target=null;keys.add(map[dir])}else keys.delete(map[dir])}
async function open(){loadPrefs();$('rh-world-launch')?.classList.add('hidden');$('classic-online-games')?.classList.add('hidden');$('game-lobby')?.classList.add('hidden');$('rh-world-shell')?.classList.remove('hidden');document.querySelectorAll('[data-rh-avatar]').forEach(b=>b.classList.toggle('active',b.dataset.rhAvatar===me.avatar));running=true;last=performance.now();await initChannel();tabState();if(!frame)frame=requestAnimationFrame(loop);$('rh-world-shell')?.scrollIntoView({behavior:'smooth',block:'start'});addFeed('World','Welcome! Map पर tap करें या controls से चलें।')}
async function close(){running=false;cancelAnimationFrame(frame);frame=0;keys.clear();target=null;$('rh-world-shell')?.classList.add('hidden');$('rh-world-launch')?.classList.remove('hidden');$('classic-online-games')?.classList.remove('hidden');$('game-lobby')?.classList.remove('hidden');if(ch){try{await ch.untrack();await db.removeChannel(ch)}catch{}ch=null;window.rhWorldChannel=null}}
async function cleanup(){await close();people.clear();feed=[]}
function init(){const c=$('rh-world-canvas');if(c){c.width=W;c.height=H;c.addEventListener('pointerdown',canvasTap)}$('rh-world-chat-input')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();sendChat()}});window.addEventListener('keydown',e=>{if(!visible()||/input|textarea/i.test(e.target.tagName))return;const k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown','w','a','s','d'].includes(k)){e.preventDefault();target=null;keys.add(k)}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));document.querySelectorAll('[data-rh-world-scene]').forEach(b=>b.addEventListener('click',()=>setScene(b.dataset.rhWorldScene==='room-self'?`room:${uid()}`:b.dataset.rhWorldScene)));document.querySelectorAll('[data-rh-avatar]').forEach(b=>b.addEventListener('click',()=>chooseAvatar(b.dataset.rhAvatar)))}
window.rhWorldOpen=open;window.rhWorldClose=close;window.rhWorldCleanup=cleanup;window.rhWorldSendChat=sendChat;window.rhWorldVisit=visit;window.rhWorldDpad=dpad;window.rhWorldAddFurniture=addFurniture;window.rhWorldClearRoom=clearRoom;window.rhWorldSetScene=setScene;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
