(()=>{
'use strict';
let link=null,score=null,top15=[];
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toastMsg(m,ok=true){try{window.toast?window.toast(m,ok):console.log(m)}catch(e){console.log(m)}}
function hideTelegram(){const s=document.getElementById('section-telegramscore');if(s){s.classList.add('hidden');s.setAttribute('hidden','')}document.getElementById('btn-telegramscore')?.classList.remove('rh-active','active');document.getElementById('btn-telegramscore-mobile')?.classList.remove('rh-active','active');clearInterval(window.__tgLbTimer)}
function hideAllSections(){document.querySelectorAll('section[id^="section-"]').forEach(x=>{x.classList.add('hidden');x.setAttribute('hidden','')});document.querySelectorAll('.rh-nav-btn').forEach(x=>x.classList.remove('rh-active','active'));document.querySelectorAll('.rh-mobile-bottom button').forEach(x=>x.classList.remove('rh-active','active'))}
function addButtons(){
 if(!document.getElementById('btn-telegramscore')){const b=document.createElement('button');b.id='btn-telegramscore';b.className='rh-nav-btn';b.type='button';b.onclick=()=>openTelegramScore();b.innerHTML='<i class="fa-brands fa-telegram" style="color:#38bdf8"></i><span>Telegram Score</span>';(document.getElementById('btn-leaderboard')||document.querySelector('.rh-nav-btn:last-of-type'))?.before(b)}
 const bar=document.querySelector('.rh-mobile-bottom');if(bar&&!document.getElementById('btn-telegramscore-mobile')){const b=document.createElement('button');b.id='btn-telegramscore-mobile';b.type='button';b.onclick=()=>openTelegramScore();b.innerHTML='<i class="fa-brands fa-telegram" style="color:#38bdf8"></i><span>Telegram</span>';bar.appendChild(b)}
}
function ensureSection(){if(document.getElementById('section-telegramscore'))return;const s=document.createElement('section');s.id='section-telegramscore';s.className='hidden space-y-5';s.setAttribute('hidden','');s.innerHTML=`<div class="rounded-3xl border border-sky-400/30 bg-gradient-to-br from-slate-950 via-sky-950/60 to-indigo-950/40 p-5 sm:p-7"><div class="flex items-start justify-between gap-3"><div><div class="text-[10px] font-black tracking-widest text-sky-300">TELEGRAM PYQ QUIZ</div><h2 class="text-2xl font-black">Telegram Leaderboard</h2><p class="mt-2 text-xs text-slate-400">सही उत्तर <b class="text-emerald-300">+20 XP</b> • गलत उत्तर <b class="text-rose-300">−10 XP</b> • <b class="text-sky-300">Top 15</b></p></div><button onclick="loadTelegramScore()" class="rh-icon-btn" aria-label="Refresh"><i class="fa-solid fa-rotate"></i></button></div><div class="mt-5 grid grid-cols-2 sm:grid-cols-4 gap-2 text-center"><div class="rounded-2xl bg-black/25 p-3"><b id="tg-xp" class="text-2xl text-sky-300">0</b><small class="block text-slate-500">XP</small></div><div class="rounded-2xl bg-black/25 p-3"><b id="tg-ok" class="text-2xl text-emerald-300">0</b><small class="block text-slate-500">CORRECT</small></div><div class="rounded-2xl bg-black/25 p-3"><b id="tg-bad" class="text-2xl text-rose-300">0</b><small class="block text-slate-500">WRONG</small></div><div class="rounded-2xl bg-black/25 p-3"><b id="tg-acc" class="text-2xl text-violet-300">0%</b><small class="block text-slate-500">ACCURACY</small></div></div></div><div id="tg-panel" class="rounded-3xl border border-slate-800 bg-slate-950/90 p-5">Loading…</div>`;(document.querySelector('.rh-content')||document.querySelector('main')||document.body).appendChild(s)}
function hookSwitch(){const old=window.switchTab;if(typeof old==='function'&&!old.__tgIsolationFix){window.switchTab=function(tab){hideTelegram();return old.apply(this,arguments)};window.switchTab.__tgIsolationFix=true}}
function addVaultCoupon(){const v=document.getElementById('section-vault');if(!v||document.getElementById('vault-coupon-card'))return;const card=document.createElement('div');card.id='vault-coupon-card';card.className='rounded-3xl border border-cyan-400/25 bg-cyan-500/5 p-4 sm:p-5';card.innerHTML='<div class="flex flex-wrap items-center justify-between gap-3"><div><b class="text-cyan-200">🎟️ Latest Coupon Code</b><p class="mt-1 text-xs text-slate-400">Admin generate kare to coupon yahan dikhega.</p></div><button onclick="loadVaultCouponCode()" class="rounded-xl bg-cyan-600 px-4 py-2.5 text-xs font-black">Refresh Code</button></div><div id="vault-coupon-code" class="mt-3 rounded-2xl bg-slate-950 p-3 text-sm text-cyan-200">Code load karne ke liye Refresh dabao.</div>';v.prepend(card)}
window.loadVaultCouponCode=async function(){const box=document.getElementById('vault-coupon-code');if(!box)return;try{let text='';if(window.hubCouponAccess?.code)text=window.hubCouponAccess.code;if(!text&&window.db){try{const r=await db.rpc('get_hub_coupon_access');if(r.data?.code)text=r.data.code}catch(e){}}
box.innerHTML=text?'<b class="text-white">'+E(text)+'</b>':'Abhi active coupon code nahi mila. Admin generate karega to yahan dikhega.'}catch(e){box.textContent='Coupon code load nahi ho saka.'}}
function calcAcc(r){const a=+r?.answer_count||0,c=+r?.correct_count||0;return a?Math.round(c/a*100):0}
function renderTop15(container){const rows=top15||[];container.innerHTML=`<div class="flex items-center justify-between gap-3"><div><div class="text-[10px] font-black tracking-widest text-sky-300">LEADERBOARD</div><div class="text-xl font-black">Top 15 Telegram Users</div></div><div class="text-right text-[11px] text-slate-500">Auto refresh: 10s</div></div><div class="mt-4 grid gap-3 sm:grid-cols-2">${rows.map(r=>{const name=r.telegram_name||r.telegram_username||'Telegram User',acc=r.accuracy??calcAcc(r),rank=r.rank||'',xp=+r.total_xp||0,correct=+r.correct_count||0,wrong=+r.wrong_count||0;return `<div class="rounded-3xl border ${rank==1?'border-amber-500/30':'border-slate-800/70'} bg-gradient-to-br from-slate-950 to-indigo-950/40 p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><div class="truncate font-black text-slate-100">${rank==1?'👑 ':''}#${E(rank)} ${E(name)}</div><div class="text-[11px] text-slate-500">${r.telegram_username?'@'+E(r.telegram_username):'ID '+E(r.telegram_user_id||'')}</div></div><div class="text-right"><div class="text-lg font-black text-sky-300">${xp} XP</div></div></div><div class="mt-3 grid grid-cols-3 gap-2 text-center"><div class="rounded-2xl bg-black/25 p-2"><div class="text-xs font-black text-emerald-300">✅ ${correct}</div></div><div class="rounded-2xl bg-black/25 p-2"><div class="text-xs font-black text-rose-300">❌ ${wrong}</div></div><div class="rounded-2xl bg-black/25 p-2"><div class="text-xs font-black text-violet-300">🎯 ${acc}%</div></div></div></div>`}).join('')||'<div class="text-slate-500">No data yet.</div>'}</div><div class="mt-5 rounded-3xl border border-slate-800 bg-black/20 p-4"><div class="text-sm font-black text-slate-100">Connect your Telegram</div><div class="mt-1 text-xs text-slate-500">App se code generate karke bot me /link CODE bhejo.</div><div id="tg-link-box" class="mt-3"></div></div>`}
function render(){const a=+score?.answer_count||0,c=+score?.correct_count||0;[['tg-xp',+score?.total_xp||0],['tg-ok',c],['tg-bad',+score?.wrong_count||0],['tg-acc',(a?Math.round(c/a*100):0)+'%']].forEach(([id,v])=>{const n=document.getElementById(id);if(n)n.textContent=v});const p=document.getElementById('tg-panel');if(p)renderTop15(p);const box=document.getElementById('tg-link-box');if(!box)return;if(link?.telegram_user_id){box.innerHTML=`<div class="text-emerald-300 font-black">✓ TELEGRAM CONNECTED</div><div class="mt-1 text-sm font-black text-slate-100">${E(link.telegram_name||'Telegram User')}</div>`}else{const valid=link?.link_code&&new Date(link.code_expires_at)>new Date();box.innerHTML=valid?`<code class="block rounded-2xl bg-black/30 px-3 py-2 text-slate-200">/link ${E(link.link_code)}</code>`:`<button class="rounded-2xl bg-sky-600 px-5 py-3 font-black" onclick="createTelegramLinkCode()">Generate Link Code</button>`}}
window.createTelegramLinkCode=async()=>{try{let{data,error}=await db.rpc('create_telegram_link_code');if(error)throw error;link={...(link||{}),link_code:data.code,code_expires_at:data.expires_at};render();toastMsg('Link code ready ✓')}catch(e){toastMsg(e.message||'Code नहीं बना',false)}};
window.loadTelegramScore=async()=>{try{const res=await db.rpc('get_telegram_top15');if(res.error)throw res.error;top15=res.data||[];try{if(window.user)await db.rpc('claim_telegram_quiz_xp')}catch(e){}if(window.user){const [a,b]=await Promise.all([db.from('telegram_account_links').select('*').eq('app_user_id',user.id).maybeSingle(),db.from('telegram_quiz_scores').select('*').eq('app_user_id',user.id).maybeSingle()]);if(a.error)throw a.error;if(b.error)throw b.error;link=a.data;score=b.data}render()}catch(e){const p=document.getElementById('tg-panel');if(p)p.innerHTML='<b class="text-amber-300">Supabase setup pending</b><p class="mt-2 text-xs text-slate-500">Telegram score SQL setup check karein.</p>'}};
window.openTelegramScore=()=>{ensureSection();hideAllSections();const s=document.getElementById('section-telegramscore');s?.classList.remove('hidden');s?.removeAttribute('hidden');document.getElementById('btn-telegramscore')?.classList.add('rh-active');document.getElementById('btn-telegramscore-mobile')?.classList.add('rh-active');loadTelegramScore();clearInterval(window.__tgLbTimer);window.__tgLbTimer=setInterval(loadTelegramScore,10000)};
function init(){addButtons();ensureSection();hookSwitch();addVaultCoupon()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{init();setTimeout(init,1000)});else{init();setTimeout(init,1000)}
})();
