(()=>{
'use strict';
let link=null,score=null,top15=[];
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);
function toastMsg(m,ok=true){try{window.toast?window.toast(m,ok):console.log(m)}catch(e){console.log(m)}}
function hardCleanup(){
  $('coupon-access-card')?.classList.add('hidden');
  $('rh-home-telegram-widgets')?.remove();
  $('rh-upcoming-admin-coupon')?.remove();
  $('rh-upcoming-study-batches-wrap')?.remove();
  document.querySelectorAll('[id*="collection"],[class*="collection"]').forEach(el=>{try{el.remove()}catch(e){}});
}
function hideTelegram(){const s=$('section-telegramscore');if(s){s.classList.add('hidden');s.setAttribute('hidden','')}document.getElementById('btn-telegramscore')?.classList.remove('rh-active','active');document.getElementById('btn-telegramscore-mobile')?.classList.remove('rh-active','active');clearInterval(window.__tgLbTimer)}
function hideAllSections(){document.querySelectorAll('section[id^="section-"]').forEach(x=>{x.classList.add('hidden');x.setAttribute('hidden','')});document.querySelectorAll('.rh-nav-btn').forEach(x=>x.classList.remove('rh-active','active'));document.querySelectorAll('.rh-mobile-bottom button').forEach(x=>x.classList.remove('rh-active','active'))}
function addButtons(){if(!$('btn-telegramscore')){const b=document.createElement('button');b.id='btn-telegramscore';b.className='rh-nav-btn';b.type='button';b.onclick=()=>openTelegramScore();b.innerHTML='<i class="fa-brands fa-telegram" style="color:#38bdf8"></i><span>Telegram Score</span>';($('btn-leaderboard')||document.querySelector('.rh-nav-btn:last-of-type'))?.before(b)}const bar=document.querySelector('.rh-mobile-bottom');if(bar&&!$('btn-telegramscore-mobile')){const b=document.createElement('button');b.id='btn-telegramscore-mobile';b.type='button';b.onclick=()=>openTelegramScore();b.innerHTML='<i class="fa-brands fa-telegram" style="color:#38bdf8"></i><span>Telegram</span>';bar.appendChild(b)}}
function ensureSection(){if($('section-telegramscore'))return;const s=document.createElement('section');s.id='section-telegramscore';s.className='hidden space-y-5';s.setAttribute('hidden','');s.innerHTML=`<div class="rounded-3xl border border-sky-400/30 bg-gradient-to-br from-slate-950 via-sky-950/60 to-indigo-950/40 p-5 sm:p-7"><div class="flex items-start justify-between gap-3"><div><div class="text-[10px] font-black tracking-widest text-sky-300">TELEGRAM PYQ QUIZ</div><h2 class="text-2xl font-black">Telegram Leaderboard</h2><p class="mt-2 text-xs text-slate-400">सही उत्तर <b class="text-emerald-300">+20 XP</b> • गलत उत्तर <b class="text-rose-300">−10 XP</b> • <b class="text-sky-300">Top 15</b></p></div><button onclick="loadTelegramScore()" class="rh-icon-btn" aria-label="Refresh"><i class="fa-solid fa-rotate"></i></button></div><div class="mt-5 grid grid-cols-2 sm:grid-cols-4 gap-2 text-center"><div class="rounded-2xl bg-black/25 p-3"><b id="tg-xp" class="text-2xl text-sky-300">0</b><small class="block text-slate-500">XP</small></div><div class="rounded-2xl bg-black/25 p-3"><b id="tg-ok" class="text-2xl text-emerald-300">0</b><small class="block text-slate-500">CORRECT</small></div><div class="rounded-2xl bg-black/25 p-3"><b id="tg-bad" class="text-2xl text-rose-300">0</b><small class="block text-slate-500">WRONG</small></div><div class="rounded-2xl bg-black/25 p-3"><b id="tg-acc" class="text-2xl text-violet-300">0%</b><small class="block text-slate-500">ACCURACY</small></div></div></div><div id="tg-panel" class="rounded-3xl border border-slate-800 bg-slate-950/90 p-5">Loading…</div>`;(document.querySelector('.rh-content')||document.querySelector('main')||document.body).appendChild(s)}
function moveRequestedFeatures(){
  hardCleanup();
  const btnTutor=$('btn-aitutor'); if(btnTutor) btnTutor.style.display='none';
  const btnQuiz=$('btn-quiz'); if(btnQuiz) btnQuiz.style.display='none';
  const tutor=$('section-aitutor'), ai=$('section-ai');
  if(tutor&&ai&&!$('ai-doubt-tutor-box')){const box=document.createElement('div');box.id='ai-doubt-tutor-box';box.className='rounded-3xl border border-cyan-400/25 bg-slate-950/90 p-4 sm:p-5';box.innerHTML='<div class="flex flex-wrap items-center justify-between gap-3"><div><b class="text-cyan-200">🤖 AI Tutor Pro</b><p class="mt-1 text-xs text-slate-400">AI Tutor Pro yahin AI Doubt ke andar open hoga.</p></div><button id="open-tutor-inside-ai" class="rounded-xl bg-gradient-to-r from-cyan-600 to-indigo-600 px-4 py-2.5 text-xs font-black">Open AI Tutor Pro</button></div>';ai.appendChild(box);$('open-tutor-inside-ai').onclick=()=>{hideAllSections();ai.classList.remove('hidden');ai.removeAttribute('hidden');tutor.classList.remove('hidden');tutor.removeAttribute('hidden');$('btn-ai')?.classList.add('rh-active');window.initAITutorView?.();window.scrollTo({top:0})}}
  const quiz=$('section-quiz'), neet=$('section-neet720');
  if(quiz&&neet&&!$('neet720-ai-learning-box')){const box=document.createElement('div');box.id='neet720-ai-learning-box';box.className='rounded-3xl border border-violet-400/25 bg-slate-950/90 p-4 sm:p-5';box.innerHTML='<div class="flex flex-wrap items-center justify-between gap-3"><div><b class="text-violet-200">✨ AI Learning</b><p class="mt-1 text-xs text-slate-400">AI Learning ab NEET 720 ke andar open hoga.</p></div><button id="open-ai-learning-inside-neet" class="rounded-xl bg-gradient-to-r from-violet-600 to-indigo-600 px-4 py-2.5 text-xs font-black">Open AI Learning</button></div>';neet.appendChild(box);$('open-ai-learning-inside-neet').onclick=()=>{hideAllSections();neet.classList.remove('hidden');neet.removeAttribute('hidden');quiz.classList.remove('hidden');quiz.removeAttribute('hidden');$('btn-neet720')?.classList.add('rh-active');window.scrollTo({top:0})}}
  // Home feature card AI Learning should open NEET 720, not separate quiz tab
  document.querySelectorAll('[onclick="switchTab(\'quiz\')"]').forEach(el=>{if((el.textContent||'').toLowerCase().includes('ai learning'))el.setAttribute('onclick',"switchTab('neet720')")});
  // Study Power: remove Smart Daily Motivation card
  const sp=$('section-studypower'); if(sp)[...sp.querySelectorAll('h3')].forEach(h=>{if((h.textContent||'').includes('Smart Daily Motivation')) h.closest('div.bg-slate-800\/95, .rounded-2xl, div')?.remove()});
  // PDF quiz generator: only admin panel
  const pdf=$('pdf-quiz-lab'), admin=$('admin-controls-host')||$('section-adminpanel');
  if(pdf&&admin&&!$('admin-pdf-quiz-panel')){const wrap=document.createElement('div');wrap.id='admin-pdf-quiz-panel';wrap.className='hidden bg-slate-800/95 border border-amber-500/30 rounded-2xl p-5 shadow-xl';wrap.innerHTML='<div class="mb-3 flex items-center justify-between"><div><h3 class="font-bold text-amber-300">📄 PDF Question Generator</h3><p class="text-xs text-slate-400 mt-1">Admin only: PDF se quiz questions generate/schedule kare.</p></div><span class="text-[10px] bg-red-500/10 text-red-300 px-2 py-1 rounded">ADMIN ONLY</span></div>';wrap.appendChild(pdf);admin.appendChild(wrap)}
  const ap=$('admin-pdf-quiz-panel'); if(ap) ap.classList.toggle('hidden', window.profile?.role!=='admin');
  const mode=$('pdf-quiz-mode'); if(mode){[...mode.options].forEach(o=>{if(o.value==='live')o.remove()}); mode.value='9pm'}
  addVaultCoupon();
}
function addVaultCoupon(){const v=$('section-vault');if(!v||$('vault-coupon-card'))return;const card=document.createElement('div');card.id='vault-coupon-card';card.className='rounded-3xl border border-cyan-400/25 bg-cyan-500/5 p-4 sm:p-5';card.innerHTML='<div class="flex flex-wrap items-center justify-between gap-3"><div><b class="text-cyan-200">🎟️ Latest Coupon Code</b><p class="mt-1 text-xs text-slate-400">Admin generate kare to coupon yahan dikhega.</p></div><button onclick="loadVaultCouponCode()" class="rounded-xl bg-cyan-600 px-4 py-2.5 text-xs font-black">Refresh Code</button></div><div id="vault-coupon-code" class="mt-3 rounded-2xl bg-slate-950 p-3 text-sm text-cyan-200">Code load karne ke liye Refresh dabao.</div>';v.prepend(card)}
window.loadVaultCouponCode=async function(){const box=$('vault-coupon-code');if(!box)return;try{let text='';if(window.hubCouponAccess?.code)text=window.hubCouponAccess.code;if(!text&&window.db){try{const r=await db.rpc('get_hub_coupon_access');if(r.data?.code)text=r.data.code}catch(e){}}box.innerHTML=text?'<b class="text-white">'+E(text)+'</b>':'Abhi active coupon code nahi mila. Admin generate karega to yahan dikhega.'}catch(e){box.textContent='Coupon code load nahi ho saka.'}}
function hookSwitch(){const old=window.switchTab;if(typeof old==='function'&&!old.__requestedShiftFix){window.switchTab=function(tab){hideTelegram();const r=old.apply(this,arguments);setTimeout(moveRequestedFeatures,80);setTimeout(()=>{if(tab==='vault')window.loadVaultCouponCode?.()},250);return r};window.switchTab.__requestedShiftFix=true}}
function renderTop15(container){const rows=top15||[];container.innerHTML=`<div class="flex items-center justify-between gap-3"><div><div class="text-[10px] font-black tracking-widest text-sky-300">LEADERBOARD</div><div class="text-xl font-black">Top 15 Telegram Users</div></div><div class="text-right text-[11px] text-slate-500">Auto refresh: 10s</div></div><div class="mt-4 grid gap-3 sm:grid-cols-2">${rows.map(r=>`<div class="rounded-3xl border border-slate-800/70 bg-gradient-to-br from-slate-950 to-indigo-950/40 p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><div class="truncate font-black text-slate-100">${r.rank==1?'👑 ':''}#${E(r.rank||'')} ${E(r.telegram_name||r.telegram_username||'Telegram User')}</div><div class="text-[11px] text-slate-500">${r.telegram_username?'@'+E(r.telegram_username):'ID '+E(r.telegram_user_id||'')}</div></div><div class="text-right"><div class="text-lg font-black text-sky-300">${+r.total_xp||0} XP</div></div></div></div>`).join('')||'<div class="text-slate-500">No data yet.</div>'}</div><div class="mt-5 rounded-3xl border border-slate-800 bg-black/20 p-4"><div class="text-sm font-black text-slate-100">Connect your Telegram</div><div class="mt-1 text-xs text-slate-500">App se code generate karke bot me /link CODE bhejo.</div><div id="tg-link-box" class="mt-3"></div></div>`}
function render(){[['tg-xp',+score?.total_xp||0],['tg-ok',+score?.correct_count||0],['tg-bad',+score?.wrong_count||0],['tg-acc',((+score?.answer_count||0)?Math.round((+score?.correct_count||0)/(+score?.answer_count||1)*100):0)+'%']].forEach(([id,v])=>{const n=$(id);if(n)n.textContent=v});const p=$('tg-panel');if(p)renderTop15(p);const box=$('tg-link-box');if(box)box.innerHTML=link?.telegram_user_id?`<div class="text-emerald-300 font-black">✓ TELEGRAM CONNECTED</div>`:`<button class="rounded-2xl bg-sky-600 px-5 py-3 font-black" onclick="createTelegramLinkCode()">Generate Link Code</button>`}
window.createTelegramLinkCode=async()=>{try{let{data,error}=await db.rpc('create_telegram_link_code');if(error)throw error;link={...(link||{}),link_code:data.code,code_expires_at:data.expires_at};render();toastMsg('Link code ready ✓')}catch(e){toastMsg(e.message||'Code nahi bana',false)}};
window.loadTelegramScore=async()=>{try{const res=await db.rpc('get_telegram_top15');if(res.error)throw res.error;top15=res.data||[];if(window.user){const [a,b]=await Promise.all([db.from('telegram_account_links').select('*').eq('app_user_id',user.id).maybeSingle(),db.from('telegram_quiz_scores').select('*').eq('app_user_id',user.id).maybeSingle()]);link=a.data;score=b.data}render()}catch(e){const p=$('tg-panel');if(p)p.innerHTML='<b class="text-amber-300">Supabase setup pending</b>'}};
window.openTelegramScore=()=>{ensureSection();hideAllSections();const s=$('section-telegramscore');s?.classList.remove('hidden');s?.removeAttribute('hidden');$('btn-telegramscore')?.classList.add('rh-active');$('btn-telegramscore-mobile')?.classList.add('rh-active');loadTelegramScore();clearInterval(window.__tgLbTimer);window.__tgLbTimer=setInterval(loadTelegramScore,10000)};
function init(){addButtons();ensureSection();hookSwitch();moveRequestedFeatures();setTimeout(moveRequestedFeatures,1000);setTimeout(moveRequestedFeatures,2500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
